### ISSUE TITLE
.env support with the data proxy

### ISSUE THREAD

**Issue by matthewmueller** [steebchen/prisma-client-go#662]
Right now dotenv doesn't seem to be loaded in data proxy mode

```
panic: no connection string found

goroutine 1 [running]:
demo/prisma/db.NewClient()
        /Users/m/dev/src/github.com/prisma/go-client/prisma/db/db_gen.go:1396 +0x247
main.main()
        /Users/m/dev/src/github.com/prisma/go-client/main.go:11 +0x55
exit status 2
```

**Comment by steebchen** [comment]
Can you please describe where your `prisma.schema` and your env file is located?
